{
 "title": "Freebox",
 "tags": [
  "prometheus",
  "freebox"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Host on LAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "freebox_lan_reachable == 1", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Network Traffic Download (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(freebox_net_down_bytes[5m])",
     "legendFormat": "Download Usage"
    },
    { "expr": "freebox_net_bw_down_bytes / 10", "legendFormat": "Download Bandwidth" }
   ]
  },
  {
   "title": "Network Traffic Upload (bytes/sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(freebox_net_up_bytes[5m])",
     "legendFormat": "Upload Usage"
    },
    { "expr": "freebox_net_bw_up_bytes / 10", "legendFormat": "Upload Bandwidth" }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "freebox_system_fan_rpm", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "System Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "freebox_system_temp_celsius", "legendFormat": "{{name}}" }
   ]
  }
 ]
}