{
 "title": "Freebox",
 "tags": [
  "prometheus",
  "freebox"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Network Traffic by bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(freebox_net_down_bytes[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(freebox_net_up_bytes[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "freebox_system_fan_rpm", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "System Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "freebox_system_temp_celsius", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Hosts on LAN",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(freebox_lan_reachable)" }
   ]
  }
 ]
}